version: '3.8'

name: duohabbit

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: duohabbit-postgres
    environment:
      POSTGRES_DB: duohabbit_db
      POSTGRES_USER: duohabbit_user
      POSTGRES_PASSWORD: duohabbit_password  # В продакшене использовать secrets!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Хост:контейнер
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d  # Скрипты инициализации
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U duohabbit_user -d duohabbit_db"]  # Вот так правильно!
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - duohabbit-network
    restart: unless-stopped

  # Adminer (удобная веб-админка для БД - опционально)
  adminer:
    image: adminer:latest
    container_name: duohabbit-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - duohabbit-network
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - duohabbit-network
    ports:
    # Даем Web API, но оно доступно только на localhost, а оттуда его подхватит nginx и переведет на https
      - "127.0.0.1:8005:8005"
    volumes:
      - ./backend/data:/app/data
    mem_limit: 200m
    cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: duohabbit-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - duohabbit-network
    restart: unless-stopped

# Тома для персистентности данных
volumes:
  postgres_data:
    name: duohabbit-postgres-data

# Сети для изоляции
networks:
  duohabbit-network:
    name: duohabbit-network
    driver: bridge